### ISSUE TITLE
Creation of Recipe Screen

### ISSUE THREAD

**Issue by HackAsh96** [dpfernandes/memory-game-beta#21]
Can someone create the screen? Thank you. There is already the link to the page

**Comment by LucyChyzhova** [comment]
I would like to create this page

**Comment by HackAsh96** [comment]
@LucyChyzhova make sure to push first the other changes that we have discussed 💯 
Good job

**Comment by ricardoaguiar** [comment]
I'm still working on refactoring the game and board. It is proven more challenging than I expected.

**Comment by HackAsh96** [comment]
Do you need help with this? or you can figure it out? :)

**Comment by ricardoaguiar** [comment]
We can close this one no? The skeleton for the screen is done.
